### ISSUE TITLE
Support more versions?

### ISSUE THREAD

**Issue by HowardZHY** [TetraTau/Toki#1]
like 1.8/1.12 and other custom server softwares

**Comment by maestro-denery** [comment]
> like 1.8/1.12 and other custom server softwares

I don't think I'll be able to support versions older than 1.17 just because of poor tooling both spigot and paper had, it'll take way more effort than supporting modern versions. 

Speaking of custom server software, I think I'll make a Toki installer so people will be able to install Toki on them by grabbing a custom server jar file and running the installer (it should be a fork of paper), but such setups will be out of support in our discord and the issue tracker just like Paper doesn't support issues if they're happened on other softwares. 

Generally, if some mod works on plain Toki, but doesn't work on Toki installed on a custom server software, it should be reported to a mod developer, whether they want to support that software in their mods or not.

**Comment by maestro-denery** [comment]
(I'll close this issue when the installer is done, also I think I should properly setup issues like Paper)

**Comment by maestro-denery** [comment]
Closing, I've made the [toki installer](https://github.com/TetraTau/toki-installer)
